name: 'SourceMod Cvar Docs'
description: 'Automatic Markdown documentation for SourceMod plugin ConVars.'
author: 'https://github.com/Rainyan'
inputs:
  cwd:
    description: 'Current working directory.'
    default: '${{ github.workspace }}'
  code_patterns:
    description: 'RegEx pattern for code files to match.'
    default: '^.*\.(sp|inc|SP|INC)$'
  doc_patterns:
    description: 'RegEx pattern for documentation files to match.'
    default: '^.*\.(md|MD)$'
  header_patterns:
    description: 'RegEx pattern for documentation headers to match for the location of the cvar docs placeholder.'
    default: '([Cc]vars|[Cc]on[Vv]ars|[Cc]onsole [Vv]ariables)'
  dry_run:
    description: 'Whether to print the output to stdout instead of writing to file.'
    default: false
  encoding:
    description: 'Encoding to use for file read/write operations.'
    default: 'utf-8'
  format_filename:
    description: 'Formatting for the code file name, with placeholder $a. This is skipped if parsing one single code file.'
    default: '### $$a\n'
  format_cvarname:
    description: 'Formatting for the cvar name, with placeholder $a.'
    default: '* $$a\n'
  format_cvarprop:
    description: 'Formatting for the cvar property, with placeholder $a (property name), and $b (property default value).'
    default: '  * $$a: `$$b`\n'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Add action path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r "${{ github.action_path }}/requirements.txt"

    - name: Update documentation files
      shell: bash
      run: |
        if $dry_run; then
            dryrunarg="--dry-run"
        fi
        python "${{ github.action_path }}/document.py" \
        "${{ inputs.cwd }}" \
        -C "${{ inputs.code_patterns }}" \
        -D "${{ inputs.doc_patterns }}" \
        -H "${{ inputs.header_patterns }}" \
        --encoding "${{ inputs.encoding }}" \
        --format-filename "${{ inputs.format_filename }}" \
        --format-cvarname "${{ inputs.format_cvarname }}" \
        --format-cvarprop "${{ inputs.format_cvarprop }}" \
        $dryrunarg

    - name: Debug diff
      shell: bash
      run: git diff
# Branding reference: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'book-open'
  color: 'green'
