name: 'SourceMod Cvar Docs'
description: 'Automatic Markdown documentation for SourceMod plugin ConVars.'
author: 'https://github.com/Rainyan'
inputs:
  docs:
    description: 'RegEx pattern for MarkDown documents to match.'
    default: 'README.md'
  files:
    description: 'RegEx pattern for SourceMod code documents to match.'
    default: '*.sp'
  headers:
    description: 'Comma-delimited list of the Markdown headers to use as the cvar docs placeholder location. Case-insensitive, first match.'
    default: 'cvars,convars,console variables'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt

    - name: Update documentation files
    - shell: bash
      run: |
        for code in $(find . -regex "${{ inputs.files }}")
        do
          for doc in $(find . -regex "${{ inputs.docs }}")
          do
            python document.py "$code" "$doc"
          done
        done

    - name: Debug diff
      run: git diff
# Branding reference: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'book-open'
  color: 'green'
