name: Lint & type check

on: [push, pull_request]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Static type checking
      - run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install -U mypy
          mypy .
